services:
  samba:
    image: ghcr.io/servercontainers/samba:latest
    container_name: samba
    restart: unless-stopped
    ports:
      # Standard Windows/Mac SMB ports
      - "${SMB_PORT_139}:139"
      - "${SMB_PORT_445}:445"
    environment:
      # 1. Create your user and tie it perfectly to your host IDs
      - ACCOUNT_${smb_user}=${smb_password}
      - UID_${smb_user}=${PUID}
      - GID_${smb_user}=${PGID}
      
      - "SAMBA_VOLUME_CONFIG_media=[Media]; path=/media; valid users = ${smb_user}; guest ok = no; read only = no; browseable = yes"
      
      # 3. The Data Share (Read-Only vault for Nextcloud)
      - "SAMBA_VOLUME_CONFIG_data=[Data]; path=/data; valid users = ${smb_user}; guest ok = no; read only = yes; browseable = yes"

    volumes:
      - "${MEDIA_DIR}:/media"
      - "${DATA_DIR}:/data:ro"